$deploy_dir = "#{ENV['HOME']}/dev/deploy"
$source_dir = "#{ENV['HOME']}/dev/src"
$uportal_download_url = "http://downloads.jasig.org/uportal"
$cas_download_url = "http://downloads.jasig.org/cas"
$tomcat_download_url = "http://www.motorlogy.com/apache/tomcat/tomcat-6/v6.0.35/bin"